---
- name: Install Java 17 and Set Up Minecraft Server
  hosts: "{{ lookup('env', 'ANSIBLE_HOSTS') }}"
  become: yes

  tasks:
    - name: Install Java 17
      raw: | 
        sudo yum install -y java-17-amazon-corretto.x86_64

    - name: Add 'minecraft' user
      user:
        name: minecraft
        password: "{{ 'minecraftadmin123' | password_hash('sha512') }}"  # Encrypt the password
        shell: /bin/bash

    - name: Create '/opt/minecraft/server/' directory
      file:
        path: /opt/minecraft/server/
        state: directory

    - name: Set owner and group of '/opt/minecraft/server/' directory recursively
      file:
        path: /opt/minecraft/server/
        owner: minecraft
        group: minecraft
        recurse: yes

    - name: Download the newest Minecraft server
      get_url:
        url: "https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar"
        dest: "/opt/minecraft/server/server.jar"

    - name: Create Minecraft systemd service file
      template:
        src: minecraft.service.j2
        dest: /lib/systemd/system/minecraft.service
        mode: '0644'

    - name: Copy minecraft_service.sh script to /usr/bin
      copy:
        src: minecraft_service.sh
        dest: /usr/bin/minecraft_service.sh
        mode: '0755'

    - name: Start Minecraft server to generate EULA
      systemd:
        name: minecraft
        state: started
      ignore_errors: yes
      register: minecraft_service_status
      changed_when: minecraft_service_status is failed

    - name: Wait for Minecraft server to start
      wait_for:
        port: 25565
        state: started
      when: minecraft_service_status is failed

    - name: Accept the Minecraft EULA, does anyone even read these things?
      lineinfile:
        path: /opt/minecraft/server/eula.txt
        line: eula=true
      when: minecraft_service_status is failed

    - name: Stop Minecraft server
      systemd:
        name: minecraft
        state: stopped
      when: minecraft_service_status is failed

    - name: Enable and start minecraft service
      systemd:
        name: minecraft
        enabled: yes
        state: started
