---
- name: Install Java 17 and Set Up Minecraft Server
  hosts: "{{ lookup('env', 'ANSIBLE_HOSTS') }}"
  become: yes

  tasks:
    - name: Install Java 17
      raw: |
        sudo yum install -y java-17-openjdk-devel

    - name: Add 'minecraft' user
      user:
        name: minecraft
        password: "{{ 'minecraftadmin123' | password_hash('sha512') }}"  # Encrypt the password
        shell: /bin/bash

    - name: Create '/opt/minecraft/server/' directory
      file:
        path: /opt/minecraft/server/
        state: directory

    - name: Set owner and group of '/opt/minecraft/server/' directory recursively
      file:
        path: /opt/minecraft/server/
        owner: minecraft
        group: minecraft
        recurse: yes

    - name: Download the newest Minecraft server
      get_url:
        url: "https://launcher.mojang.com/v1/objects/{{ lookup('url', 'https://launchermeta.mojang.com/mc/game/version_manifest.json') | from_json | json_query('latest.release') }}/server.jar"
        dest: "/opt/minecraft/server/server.jar"

